### PR TITLE
User and Asset Management

### PR DESCRIPTION
**Pull request by Boboiboy181**

### CODE REVIEW

**Review by IamMrGru — APPROVED** [review]
I love these Features very much

**Review by michael5671 — APPROVED** [review]
quá đỉnhhhhh

**Review by taitran501 — APPROVED** [review]
Mượt điên

**Review by nguyenhuunamtruong — APPROVED** [review]
quá tuyệt

**Review by ThangWing — APPROVED** [review]
This feature is so fantastic, wonderful, significant, magnificent, outstanding

**Pull request merged**
